// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BattleFrame.proto

#include "BattleFrame.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)
class BattleFrameDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<BattleFrame>
      _instance;
} _BattleFrame_default_instance_;
namespace protobuf_BattleFrame_2eproto {
void InitDefaultsBattleFrameImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  protobuf_BattleInput_2eproto::InitDefaultsBattleInput();
  {
    void* ptr = &::_BattleFrame_default_instance_;
    new (ptr) ::BattleFrame();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::BattleFrame::InitAsDefaultInstance();
}

void InitDefaultsBattleFrame() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsBattleFrameImpl);
}

::google::protobuf::Metadata file_level_metadata[1];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::BattleFrame, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::BattleFrame, error_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::BattleFrame, framenumber_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::BattleFrame, randomcode_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::BattleFrame, battleinputs_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::BattleFrame)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::_BattleFrame_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "BattleFrame.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 1);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\021BattleFrame.proto\032\021BattleInput.proto\"i"
      "\n\013BattleFrame\022\r\n\005error\030\001 \001(\005\022\023\n\013frameNum"
      "ber\030\002 \001(\005\022\022\n\nrandomCode\030\003 \001(\005\022\"\n\014battleI"
      "nputs\030\004 \003(\0132\014.BattleInputb\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 153);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "BattleFrame.proto", &protobuf_RegisterTypes);
  ::protobuf_BattleInput_2eproto::AddDescriptors();
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_BattleFrame_2eproto

// ===================================================================

void BattleFrame::InitAsDefaultInstance() {
}
void BattleFrame::clear_battleinputs() {
  battleinputs_.Clear();
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int BattleFrame::kErrorFieldNumber;
const int BattleFrame::kFrameNumberFieldNumber;
const int BattleFrame::kRandomCodeFieldNumber;
const int BattleFrame::kBattleInputsFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

BattleFrame::BattleFrame()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_BattleFrame_2eproto::InitDefaultsBattleFrame();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:BattleFrame)
}
BattleFrame::BattleFrame(const BattleFrame& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      battleinputs_(from.battleinputs_),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&error_, &from.error_,
    static_cast<size_t>(reinterpret_cast<char*>(&randomcode_) -
    reinterpret_cast<char*>(&error_)) + sizeof(randomcode_));
  // @@protoc_insertion_point(copy_constructor:BattleFrame)
}

void BattleFrame::SharedCtor() {
  ::memset(&error_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&randomcode_) -
      reinterpret_cast<char*>(&error_)) + sizeof(randomcode_));
  _cached_size_ = 0;
}

BattleFrame::~BattleFrame() {
  // @@protoc_insertion_point(destructor:BattleFrame)
  SharedDtor();
}

void BattleFrame::SharedDtor() {
}

void BattleFrame::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* BattleFrame::descriptor() {
  ::protobuf_BattleFrame_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_BattleFrame_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const BattleFrame& BattleFrame::default_instance() {
  ::protobuf_BattleFrame_2eproto::InitDefaultsBattleFrame();
  return *internal_default_instance();
}

BattleFrame* BattleFrame::New(::google::protobuf::Arena* arena) const {
  BattleFrame* n = new BattleFrame;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void BattleFrame::Clear() {
// @@protoc_insertion_point(message_clear_start:BattleFrame)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  battleinputs_.Clear();
  ::memset(&error_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&randomcode_) -
      reinterpret_cast<char*>(&error_)) + sizeof(randomcode_));
  _internal_metadata_.Clear();
}

bool BattleFrame::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:BattleFrame)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int32 error = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &error_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 frameNumber = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &framenumber_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 randomCode = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(24u /* 24 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &randomcode_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated .BattleInput battleInputs = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(34u /* 34 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(input, add_battleinputs()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:BattleFrame)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:BattleFrame)
  return false;
#undef DO_
}

void BattleFrame::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:BattleFrame)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 error = 1;
  if (this->error() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->error(), output);
  }

  // int32 frameNumber = 2;
  if (this->framenumber() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->framenumber(), output);
  }

  // int32 randomCode = 3;
  if (this->randomcode() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(3, this->randomcode(), output);
  }

  // repeated .BattleInput battleInputs = 4;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->battleinputs_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      4, this->battleinputs(static_cast<int>(i)), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:BattleFrame)
}

::google::protobuf::uint8* BattleFrame::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:BattleFrame)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 error = 1;
  if (this->error() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->error(), target);
  }

  // int32 frameNumber = 2;
  if (this->framenumber() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->framenumber(), target);
  }

  // int32 randomCode = 3;
  if (this->randomcode() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(3, this->randomcode(), target);
  }

  // repeated .BattleInput battleInputs = 4;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->battleinputs_size()); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        4, this->battleinputs(static_cast<int>(i)), deterministic, target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:BattleFrame)
  return target;
}

size_t BattleFrame::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:BattleFrame)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // repeated .BattleInput battleInputs = 4;
  {
    unsigned int count = static_cast<unsigned int>(this->battleinputs_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          this->battleinputs(static_cast<int>(i)));
    }
  }

  // int32 error = 1;
  if (this->error() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->error());
  }

  // int32 frameNumber = 2;
  if (this->framenumber() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->framenumber());
  }

  // int32 randomCode = 3;
  if (this->randomcode() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->randomcode());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void BattleFrame::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:BattleFrame)
  GOOGLE_DCHECK_NE(&from, this);
  const BattleFrame* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const BattleFrame>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:BattleFrame)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:BattleFrame)
    MergeFrom(*source);
  }
}

void BattleFrame::MergeFrom(const BattleFrame& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:BattleFrame)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  battleinputs_.MergeFrom(from.battleinputs_);
  if (from.error() != 0) {
    set_error(from.error());
  }
  if (from.framenumber() != 0) {
    set_framenumber(from.framenumber());
  }
  if (from.randomcode() != 0) {
    set_randomcode(from.randomcode());
  }
}

void BattleFrame::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:BattleFrame)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void BattleFrame::CopyFrom(const BattleFrame& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:BattleFrame)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool BattleFrame::IsInitialized() const {
  return true;
}

void BattleFrame::Swap(BattleFrame* other) {
  if (other == this) return;
  InternalSwap(other);
}
void BattleFrame::InternalSwap(BattleFrame* other) {
  using std::swap;
  battleinputs_.InternalSwap(&other->battleinputs_);
  swap(error_, other->error_);
  swap(framenumber_, other->framenumber_);
  swap(randomcode_, other->randomcode_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata BattleFrame::GetMetadata() const {
  protobuf_BattleFrame_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_BattleFrame_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
