// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BattleFrame.proto

#ifndef PROTOBUF_BattleFrame_2eproto__INCLUDED
#define PROTOBUF_BattleFrame_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3005001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "BattleInput.pb.h"
// @@protoc_insertion_point(includes)

namespace protobuf_BattleFrame_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
void InitDefaultsBattleFrameImpl();
void InitDefaultsBattleFrame();
inline void InitDefaults() {
  InitDefaultsBattleFrame();
}
}  // namespace protobuf_BattleFrame_2eproto
class BattleFrame;
class BattleFrameDefaultTypeInternal;
extern BattleFrameDefaultTypeInternal _BattleFrame_default_instance_;

// ===================================================================

class BattleFrame : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:BattleFrame) */ {
 public:
  BattleFrame();
  virtual ~BattleFrame();

  BattleFrame(const BattleFrame& from);

  inline BattleFrame& operator=(const BattleFrame& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  BattleFrame(BattleFrame&& from) noexcept
    : BattleFrame() {
    *this = ::std::move(from);
  }

  inline BattleFrame& operator=(BattleFrame&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const BattleFrame& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const BattleFrame* internal_default_instance() {
    return reinterpret_cast<const BattleFrame*>(
               &_BattleFrame_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(BattleFrame* other);
  friend void swap(BattleFrame& a, BattleFrame& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline BattleFrame* New() const PROTOBUF_FINAL { return New(NULL); }

  BattleFrame* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const BattleFrame& from);
  void MergeFrom(const BattleFrame& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(BattleFrame* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .BattleInput battleInputs = 4;
  int battleinputs_size() const;
  void clear_battleinputs();
  static const int kBattleInputsFieldNumber = 4;
  const ::BattleInput& battleinputs(int index) const;
  ::BattleInput* mutable_battleinputs(int index);
  ::BattleInput* add_battleinputs();
  ::google::protobuf::RepeatedPtrField< ::BattleInput >*
      mutable_battleinputs();
  const ::google::protobuf::RepeatedPtrField< ::BattleInput >&
      battleinputs() const;

  // int32 error = 1;
  void clear_error();
  static const int kErrorFieldNumber = 1;
  ::google::protobuf::int32 error() const;
  void set_error(::google::protobuf::int32 value);

  // int32 frameNumber = 2;
  void clear_framenumber();
  static const int kFrameNumberFieldNumber = 2;
  ::google::protobuf::int32 framenumber() const;
  void set_framenumber(::google::protobuf::int32 value);

  // int32 randomCode = 3;
  void clear_randomcode();
  static const int kRandomCodeFieldNumber = 3;
  ::google::protobuf::int32 randomcode() const;
  void set_randomcode(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:BattleFrame)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::BattleInput > battleinputs_;
  ::google::protobuf::int32 error_;
  ::google::protobuf::int32 framenumber_;
  ::google::protobuf::int32 randomcode_;
  mutable int _cached_size_;
  friend struct ::protobuf_BattleFrame_2eproto::TableStruct;
  friend void ::protobuf_BattleFrame_2eproto::InitDefaultsBattleFrameImpl();
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// BattleFrame

// int32 error = 1;
inline void BattleFrame::clear_error() {
  error_ = 0;
}
inline ::google::protobuf::int32 BattleFrame::error() const {
  // @@protoc_insertion_point(field_get:BattleFrame.error)
  return error_;
}
inline void BattleFrame::set_error(::google::protobuf::int32 value) {
  
  error_ = value;
  // @@protoc_insertion_point(field_set:BattleFrame.error)
}

// int32 frameNumber = 2;
inline void BattleFrame::clear_framenumber() {
  framenumber_ = 0;
}
inline ::google::protobuf::int32 BattleFrame::framenumber() const {
  // @@protoc_insertion_point(field_get:BattleFrame.frameNumber)
  return framenumber_;
}
inline void BattleFrame::set_framenumber(::google::protobuf::int32 value) {
  
  framenumber_ = value;
  // @@protoc_insertion_point(field_set:BattleFrame.frameNumber)
}

// int32 randomCode = 3;
inline void BattleFrame::clear_randomcode() {
  randomcode_ = 0;
}
inline ::google::protobuf::int32 BattleFrame::randomcode() const {
  // @@protoc_insertion_point(field_get:BattleFrame.randomCode)
  return randomcode_;
}
inline void BattleFrame::set_randomcode(::google::protobuf::int32 value) {
  
  randomcode_ = value;
  // @@protoc_insertion_point(field_set:BattleFrame.randomCode)
}

// repeated .BattleInput battleInputs = 4;
inline int BattleFrame::battleinputs_size() const {
  return battleinputs_.size();
}
inline const ::BattleInput& BattleFrame::battleinputs(int index) const {
  // @@protoc_insertion_point(field_get:BattleFrame.battleInputs)
  return battleinputs_.Get(index);
}
inline ::BattleInput* BattleFrame::mutable_battleinputs(int index) {
  // @@protoc_insertion_point(field_mutable:BattleFrame.battleInputs)
  return battleinputs_.Mutable(index);
}
inline ::BattleInput* BattleFrame::add_battleinputs() {
  // @@protoc_insertion_point(field_add:BattleFrame.battleInputs)
  return battleinputs_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::BattleInput >*
BattleFrame::mutable_battleinputs() {
  // @@protoc_insertion_point(field_mutable_list:BattleFrame.battleInputs)
  return &battleinputs_;
}
inline const ::google::protobuf::RepeatedPtrField< ::BattleInput >&
BattleFrame::battleinputs() const {
  // @@protoc_insertion_point(field_list:BattleFrame.battleInputs)
  return battleinputs_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_BattleFrame_2eproto__INCLUDED
