// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ChangeRoleC2S.proto

#include "ChangeRoleC2S.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)
class ChangeRoleC2SDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<ChangeRoleC2S>
      _instance;
} _ChangeRoleC2S_default_instance_;
namespace protobuf_ChangeRoleC2S_2eproto {
void InitDefaultsChangeRoleC2SImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  {
    void* ptr = &::_ChangeRoleC2S_default_instance_;
    new (ptr) ::ChangeRoleC2S();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::ChangeRoleC2S::InitAsDefaultInstance();
}

void InitDefaultsChangeRoleC2S() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsChangeRoleC2SImpl);
}

::google::protobuf::Metadata file_level_metadata[1];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::ChangeRoleC2S, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::ChangeRoleC2S, role_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::ChangeRoleC2S)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::_ChangeRoleC2S_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "ChangeRoleC2S.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 1);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\023ChangeRoleC2S.proto\032\020PlayerInfo.proto\""
      "$\n\rChangeRoleC2S\022\023\n\004role\030\001 \001(\0162\005.Roleb\006p"
      "roto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 85);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "ChangeRoleC2S.proto", &protobuf_RegisterTypes);
  ::protobuf_PlayerInfo_2eproto::AddDescriptors();
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_ChangeRoleC2S_2eproto

// ===================================================================

void ChangeRoleC2S::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ChangeRoleC2S::kRoleFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ChangeRoleC2S::ChangeRoleC2S()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_ChangeRoleC2S_2eproto::InitDefaultsChangeRoleC2S();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:ChangeRoleC2S)
}
ChangeRoleC2S::ChangeRoleC2S(const ChangeRoleC2S& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  role_ = from.role_;
  // @@protoc_insertion_point(copy_constructor:ChangeRoleC2S)
}

void ChangeRoleC2S::SharedCtor() {
  role_ = 0;
  _cached_size_ = 0;
}

ChangeRoleC2S::~ChangeRoleC2S() {
  // @@protoc_insertion_point(destructor:ChangeRoleC2S)
  SharedDtor();
}

void ChangeRoleC2S::SharedDtor() {
}

void ChangeRoleC2S::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* ChangeRoleC2S::descriptor() {
  ::protobuf_ChangeRoleC2S_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_ChangeRoleC2S_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const ChangeRoleC2S& ChangeRoleC2S::default_instance() {
  ::protobuf_ChangeRoleC2S_2eproto::InitDefaultsChangeRoleC2S();
  return *internal_default_instance();
}

ChangeRoleC2S* ChangeRoleC2S::New(::google::protobuf::Arena* arena) const {
  ChangeRoleC2S* n = new ChangeRoleC2S;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void ChangeRoleC2S::Clear() {
// @@protoc_insertion_point(message_clear_start:ChangeRoleC2S)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  role_ = 0;
  _internal_metadata_.Clear();
}

bool ChangeRoleC2S::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:ChangeRoleC2S)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // .Role role = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_role(static_cast< ::Role >(value));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:ChangeRoleC2S)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:ChangeRoleC2S)
  return false;
#undef DO_
}

void ChangeRoleC2S::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:ChangeRoleC2S)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .Role role = 1;
  if (this->role() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      1, this->role(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:ChangeRoleC2S)
}

::google::protobuf::uint8* ChangeRoleC2S::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:ChangeRoleC2S)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .Role role = 1;
  if (this->role() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      1, this->role(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ChangeRoleC2S)
  return target;
}

size_t ChangeRoleC2S::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ChangeRoleC2S)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // .Role role = 1;
  if (this->role() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->role());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void ChangeRoleC2S::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:ChangeRoleC2S)
  GOOGLE_DCHECK_NE(&from, this);
  const ChangeRoleC2S* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const ChangeRoleC2S>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:ChangeRoleC2S)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:ChangeRoleC2S)
    MergeFrom(*source);
  }
}

void ChangeRoleC2S::MergeFrom(const ChangeRoleC2S& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:ChangeRoleC2S)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.role() != 0) {
    set_role(from.role());
  }
}

void ChangeRoleC2S::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:ChangeRoleC2S)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ChangeRoleC2S::CopyFrom(const ChangeRoleC2S& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ChangeRoleC2S)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ChangeRoleC2S::IsInitialized() const {
  return true;
}

void ChangeRoleC2S::Swap(ChangeRoleC2S* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ChangeRoleC2S::InternalSwap(ChangeRoleC2S* other) {
  using std::swap;
  swap(role_, other->role_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata ChangeRoleC2S::GetMetadata() const {
  protobuf_ChangeRoleC2S_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_ChangeRoleC2S_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
