// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GetRoomInfoS2C.proto

#ifndef PROTOBUF_GetRoomInfoS2C_2eproto__INCLUDED
#define PROTOBUF_GetRoomInfoS2C_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3005001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "PlayerInfo.pb.h"
// @@protoc_insertion_point(includes)

namespace protobuf_GetRoomInfoS2C_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
void InitDefaultsGetRoomInfoS2CImpl();
void InitDefaultsGetRoomInfoS2C();
inline void InitDefaults() {
  InitDefaultsGetRoomInfoS2C();
}
}  // namespace protobuf_GetRoomInfoS2C_2eproto
class GetRoomInfoS2C;
class GetRoomInfoS2CDefaultTypeInternal;
extern GetRoomInfoS2CDefaultTypeInternal _GetRoomInfoS2C_default_instance_;

// ===================================================================

class GetRoomInfoS2C : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:GetRoomInfoS2C) */ {
 public:
  GetRoomInfoS2C();
  virtual ~GetRoomInfoS2C();

  GetRoomInfoS2C(const GetRoomInfoS2C& from);

  inline GetRoomInfoS2C& operator=(const GetRoomInfoS2C& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  GetRoomInfoS2C(GetRoomInfoS2C&& from) noexcept
    : GetRoomInfoS2C() {
    *this = ::std::move(from);
  }

  inline GetRoomInfoS2C& operator=(GetRoomInfoS2C&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const GetRoomInfoS2C& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const GetRoomInfoS2C* internal_default_instance() {
    return reinterpret_cast<const GetRoomInfoS2C*>(
               &_GetRoomInfoS2C_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(GetRoomInfoS2C* other);
  friend void swap(GetRoomInfoS2C& a, GetRoomInfoS2C& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline GetRoomInfoS2C* New() const PROTOBUF_FINAL { return New(NULL); }

  GetRoomInfoS2C* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const GetRoomInfoS2C& from);
  void MergeFrom(const GetRoomInfoS2C& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(GetRoomInfoS2C* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .PlayerInfo playersInfo = 4;
  int playersinfo_size() const;
  void clear_playersinfo();
  static const int kPlayersInfoFieldNumber = 4;
  const ::PlayerInfo& playersinfo(int index) const;
  ::PlayerInfo* mutable_playersinfo(int index);
  ::PlayerInfo* add_playersinfo();
  ::google::protobuf::RepeatedPtrField< ::PlayerInfo >*
      mutable_playersinfo();
  const ::google::protobuf::RepeatedPtrField< ::PlayerInfo >&
      playersinfo() const;

  // int32 error = 1;
  void clear_error();
  static const int kErrorFieldNumber = 1;
  ::google::protobuf::int32 error() const;
  void set_error(::google::protobuf::int32 value);

  // bool succeed = 2;
  void clear_succeed();
  static const int kSucceedFieldNumber = 2;
  bool succeed() const;
  void set_succeed(bool value);

  // int32 roomOwnerId = 3;
  void clear_roomownerid();
  static const int kRoomOwnerIdFieldNumber = 3;
  ::google::protobuf::int32 roomownerid() const;
  void set_roomownerid(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:GetRoomInfoS2C)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::PlayerInfo > playersinfo_;
  ::google::protobuf::int32 error_;
  bool succeed_;
  ::google::protobuf::int32 roomownerid_;
  mutable int _cached_size_;
  friend struct ::protobuf_GetRoomInfoS2C_2eproto::TableStruct;
  friend void ::protobuf_GetRoomInfoS2C_2eproto::InitDefaultsGetRoomInfoS2CImpl();
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// GetRoomInfoS2C

// int32 error = 1;
inline void GetRoomInfoS2C::clear_error() {
  error_ = 0;
}
inline ::google::protobuf::int32 GetRoomInfoS2C::error() const {
  // @@protoc_insertion_point(field_get:GetRoomInfoS2C.error)
  return error_;
}
inline void GetRoomInfoS2C::set_error(::google::protobuf::int32 value) {
  
  error_ = value;
  // @@protoc_insertion_point(field_set:GetRoomInfoS2C.error)
}

// bool succeed = 2;
inline void GetRoomInfoS2C::clear_succeed() {
  succeed_ = false;
}
inline bool GetRoomInfoS2C::succeed() const {
  // @@protoc_insertion_point(field_get:GetRoomInfoS2C.succeed)
  return succeed_;
}
inline void GetRoomInfoS2C::set_succeed(bool value) {
  
  succeed_ = value;
  // @@protoc_insertion_point(field_set:GetRoomInfoS2C.succeed)
}

// int32 roomOwnerId = 3;
inline void GetRoomInfoS2C::clear_roomownerid() {
  roomownerid_ = 0;
}
inline ::google::protobuf::int32 GetRoomInfoS2C::roomownerid() const {
  // @@protoc_insertion_point(field_get:GetRoomInfoS2C.roomOwnerId)
  return roomownerid_;
}
inline void GetRoomInfoS2C::set_roomownerid(::google::protobuf::int32 value) {
  
  roomownerid_ = value;
  // @@protoc_insertion_point(field_set:GetRoomInfoS2C.roomOwnerId)
}

// repeated .PlayerInfo playersInfo = 4;
inline int GetRoomInfoS2C::playersinfo_size() const {
  return playersinfo_.size();
}
inline const ::PlayerInfo& GetRoomInfoS2C::playersinfo(int index) const {
  // @@protoc_insertion_point(field_get:GetRoomInfoS2C.playersInfo)
  return playersinfo_.Get(index);
}
inline ::PlayerInfo* GetRoomInfoS2C::mutable_playersinfo(int index) {
  // @@protoc_insertion_point(field_mutable:GetRoomInfoS2C.playersInfo)
  return playersinfo_.Mutable(index);
}
inline ::PlayerInfo* GetRoomInfoS2C::add_playersinfo() {
  // @@protoc_insertion_point(field_add:GetRoomInfoS2C.playersInfo)
  return playersinfo_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::PlayerInfo >*
GetRoomInfoS2C::mutable_playersinfo() {
  // @@protoc_insertion_point(field_mutable_list:GetRoomInfoS2C.playersInfo)
  return &playersinfo_;
}
inline const ::google::protobuf::RepeatedPtrField< ::PlayerInfo >&
GetRoomInfoS2C::playersinfo() const {
  // @@protoc_insertion_point(field_list:GetRoomInfoS2C.playersInfo)
  return playersinfo_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_GetRoomInfoS2C_2eproto__INCLUDED
