// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NextFloorC2S.proto

#ifndef PROTOBUF_NextFloorC2S_2eproto__INCLUDED
#define PROTOBUF_NextFloorC2S_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3005001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace protobuf_NextFloorC2S_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
void InitDefaultsNextFloorC2SImpl();
void InitDefaultsNextFloorC2S();
inline void InitDefaults() {
  InitDefaultsNextFloorC2S();
}
}  // namespace protobuf_NextFloorC2S_2eproto
class NextFloorC2S;
class NextFloorC2SDefaultTypeInternal;
extern NextFloorC2SDefaultTypeInternal _NextFloorC2S_default_instance_;

// ===================================================================

class NextFloorC2S : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:NextFloorC2S) */ {
 public:
  NextFloorC2S();
  virtual ~NextFloorC2S();

  NextFloorC2S(const NextFloorC2S& from);

  inline NextFloorC2S& operator=(const NextFloorC2S& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  NextFloorC2S(NextFloorC2S&& from) noexcept
    : NextFloorC2S() {
    *this = ::std::move(from);
  }

  inline NextFloorC2S& operator=(NextFloorC2S&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const NextFloorC2S& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const NextFloorC2S* internal_default_instance() {
    return reinterpret_cast<const NextFloorC2S*>(
               &_NextFloorC2S_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(NextFloorC2S* other);
  friend void swap(NextFloorC2S& a, NextFloorC2S& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline NextFloorC2S* New() const PROTOBUF_FINAL { return New(NULL); }

  NextFloorC2S* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const NextFloorC2S& from);
  void MergeFrom(const NextFloorC2S& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(NextFloorC2S* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // int32 floorNumber = 1;
  void clear_floornumber();
  static const int kFloorNumberFieldNumber = 1;
  ::google::protobuf::int32 floornumber() const;
  void set_floornumber(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:NextFloorC2S)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int32 floornumber_;
  mutable int _cached_size_;
  friend struct ::protobuf_NextFloorC2S_2eproto::TableStruct;
  friend void ::protobuf_NextFloorC2S_2eproto::InitDefaultsNextFloorC2SImpl();
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// NextFloorC2S

// int32 floorNumber = 1;
inline void NextFloorC2S::clear_floornumber() {
  floornumber_ = 0;
}
inline ::google::protobuf::int32 NextFloorC2S::floornumber() const {
  // @@protoc_insertion_point(field_get:NextFloorC2S.floorNumber)
  return floornumber_;
}
inline void NextFloorC2S::set_floornumber(::google::protobuf::int32 value) {
  
  floornumber_ = value;
  // @@protoc_insertion_point(field_set:NextFloorC2S.floorNumber)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_NextFloorC2S_2eproto__INCLUDED
