// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: StartGameS2C.proto

#ifndef PROTOBUF_StartGameS2C_2eproto__INCLUDED
#define PROTOBUF_StartGameS2C_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3005001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "PlayerInfo.pb.h"
// @@protoc_insertion_point(includes)

namespace protobuf_StartGameS2C_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
void InitDefaultsStartGameS2CImpl();
void InitDefaultsStartGameS2C();
inline void InitDefaults() {
  InitDefaultsStartGameS2C();
}
}  // namespace protobuf_StartGameS2C_2eproto
class StartGameS2C;
class StartGameS2CDefaultTypeInternal;
extern StartGameS2CDefaultTypeInternal _StartGameS2C_default_instance_;

// ===================================================================

class StartGameS2C : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:StartGameS2C) */ {
 public:
  StartGameS2C();
  virtual ~StartGameS2C();

  StartGameS2C(const StartGameS2C& from);

  inline StartGameS2C& operator=(const StartGameS2C& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  StartGameS2C(StartGameS2C&& from) noexcept
    : StartGameS2C() {
    *this = ::std::move(from);
  }

  inline StartGameS2C& operator=(StartGameS2C&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const StartGameS2C& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const StartGameS2C* internal_default_instance() {
    return reinterpret_cast<const StartGameS2C*>(
               &_StartGameS2C_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(StartGameS2C* other);
  friend void swap(StartGameS2C& a, StartGameS2C& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline StartGameS2C* New() const PROTOBUF_FINAL { return New(NULL); }

  StartGameS2C* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const StartGameS2C& from);
  void MergeFrom(const StartGameS2C& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(StartGameS2C* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .PlayerInfo playersInfo = 6;
  int playersinfo_size() const;
  void clear_playersinfo();
  static const int kPlayersInfoFieldNumber = 6;
  const ::PlayerInfo& playersinfo(int index) const;
  ::PlayerInfo* mutable_playersinfo(int index);
  ::PlayerInfo* add_playersinfo();
  ::google::protobuf::RepeatedPtrField< ::PlayerInfo >*
      mutable_playersinfo();
  const ::google::protobuf::RepeatedPtrField< ::PlayerInfo >&
      playersinfo() const;

  // int32 error = 1;
  void clear_error();
  static const int kErrorFieldNumber = 1;
  ::google::protobuf::int32 error() const;
  void set_error(::google::protobuf::int32 value);

  // bool succeed = 2;
  void clear_succeed();
  static const int kSucceedFieldNumber = 2;
  bool succeed() const;
  void set_succeed(bool value);

  // int32 seed = 3;
  void clear_seed();
  static const int kSeedFieldNumber = 3;
  ::google::protobuf::int32 seed() const;
  void set_seed(::google::protobuf::int32 value);

  // int32 floorNumber = 4;
  void clear_floornumber();
  static const int kFloorNumberFieldNumber = 4;
  ::google::protobuf::int32 floornumber() const;
  void set_floornumber(::google::protobuf::int32 value);

  // int32 maxFloorNumber = 5;
  void clear_maxfloornumber();
  static const int kMaxFloorNumberFieldNumber = 5;
  ::google::protobuf::int32 maxfloornumber() const;
  void set_maxfloornumber(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:StartGameS2C)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::PlayerInfo > playersinfo_;
  ::google::protobuf::int32 error_;
  bool succeed_;
  ::google::protobuf::int32 seed_;
  ::google::protobuf::int32 floornumber_;
  ::google::protobuf::int32 maxfloornumber_;
  mutable int _cached_size_;
  friend struct ::protobuf_StartGameS2C_2eproto::TableStruct;
  friend void ::protobuf_StartGameS2C_2eproto::InitDefaultsStartGameS2CImpl();
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// StartGameS2C

// int32 error = 1;
inline void StartGameS2C::clear_error() {
  error_ = 0;
}
inline ::google::protobuf::int32 StartGameS2C::error() const {
  // @@protoc_insertion_point(field_get:StartGameS2C.error)
  return error_;
}
inline void StartGameS2C::set_error(::google::protobuf::int32 value) {
  
  error_ = value;
  // @@protoc_insertion_point(field_set:StartGameS2C.error)
}

// bool succeed = 2;
inline void StartGameS2C::clear_succeed() {
  succeed_ = false;
}
inline bool StartGameS2C::succeed() const {
  // @@protoc_insertion_point(field_get:StartGameS2C.succeed)
  return succeed_;
}
inline void StartGameS2C::set_succeed(bool value) {
  
  succeed_ = value;
  // @@protoc_insertion_point(field_set:StartGameS2C.succeed)
}

// int32 seed = 3;
inline void StartGameS2C::clear_seed() {
  seed_ = 0;
}
inline ::google::protobuf::int32 StartGameS2C::seed() const {
  // @@protoc_insertion_point(field_get:StartGameS2C.seed)
  return seed_;
}
inline void StartGameS2C::set_seed(::google::protobuf::int32 value) {
  
  seed_ = value;
  // @@protoc_insertion_point(field_set:StartGameS2C.seed)
}

// int32 floorNumber = 4;
inline void StartGameS2C::clear_floornumber() {
  floornumber_ = 0;
}
inline ::google::protobuf::int32 StartGameS2C::floornumber() const {
  // @@protoc_insertion_point(field_get:StartGameS2C.floorNumber)
  return floornumber_;
}
inline void StartGameS2C::set_floornumber(::google::protobuf::int32 value) {
  
  floornumber_ = value;
  // @@protoc_insertion_point(field_set:StartGameS2C.floorNumber)
}

// int32 maxFloorNumber = 5;
inline void StartGameS2C::clear_maxfloornumber() {
  maxfloornumber_ = 0;
}
inline ::google::protobuf::int32 StartGameS2C::maxfloornumber() const {
  // @@protoc_insertion_point(field_get:StartGameS2C.maxFloorNumber)
  return maxfloornumber_;
}
inline void StartGameS2C::set_maxfloornumber(::google::protobuf::int32 value) {
  
  maxfloornumber_ = value;
  // @@protoc_insertion_point(field_set:StartGameS2C.maxFloorNumber)
}

// repeated .PlayerInfo playersInfo = 6;
inline int StartGameS2C::playersinfo_size() const {
  return playersinfo_.size();
}
inline const ::PlayerInfo& StartGameS2C::playersinfo(int index) const {
  // @@protoc_insertion_point(field_get:StartGameS2C.playersInfo)
  return playersinfo_.Get(index);
}
inline ::PlayerInfo* StartGameS2C::mutable_playersinfo(int index) {
  // @@protoc_insertion_point(field_mutable:StartGameS2C.playersInfo)
  return playersinfo_.Mutable(index);
}
inline ::PlayerInfo* StartGameS2C::add_playersinfo() {
  // @@protoc_insertion_point(field_add:StartGameS2C.playersInfo)
  return playersinfo_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::PlayerInfo >*
StartGameS2C::mutable_playersinfo() {
  // @@protoc_insertion_point(field_mutable_list:StartGameS2C.playersInfo)
  return &playersinfo_;
}
inline const ::google::protobuf::RepeatedPtrField< ::PlayerInfo >&
StartGameS2C::playersinfo() const {
  // @@protoc_insertion_point(field_list:StartGameS2C.playersInfo)
  return playersinfo_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_StartGameS2C_2eproto__INCLUDED
